export const USER_SELECT = `
  u.id as "Id",
  u.username as "Username",
  u.email as "Email",
  u.first_name as "FirstName",
  u.last_name as "LastName",
  u.bio as "Bio",
  u.avatar as "Avatar",
  u.created_at as "CreatedAt",
  u.last_online as "LastOnline",
  u.last_login_at as "LastLoginAt",
  u.email_verified as "EmailVerified",
  u.two_factor_enabled as "TwoFactorEnabled",
  u.is_admin as "IsAdmin",
  u.is_owner as "IsOwner",
  u.is_disabled as "IsDisabled",
  u.is_hidden as "IsHidden",
  u.locked_until as "LockedUntil",
  u.failed_login_count as "FailedLoginCount",
  u.force_password_change as "ForcePasswordChange",
  u.login_attempts_before_lockout as "LoginAttemptsBeforeLockout",
  u.session_version as "SessionVersion",
  u.policy_json as "PolicyJson"
`;
