import type { AddItemUseCase } from './add-item.use-case';
import type { ListItemsUseCase } from './list-items.use-case';
import type { ClaimItemUseCase } from './claim-item.use-case';
import type { ClaimItemWithLinkedUseCase } from './claim-item-with-linked.use-case';
import type { AddItemLinkUseCase } from './add-item-link.use-case';
import type { DeleteItemUseCase } from './delete-item.use-case';
import type { UpdateItemUseCase } from './update-item.use-case';
import type { GetFieldDefinitionsUseCase } from './get-field-definitions.use-case';
import type { UnclaimItemUseCase } from './unclaim-item.use-case';
import type { UnclaimItemWithLinkedUseCase } from './unclaim-item-with-linked.use-case';
import type { ValidateItemAudienceUseCase } from './validate-item-audience.use-case';
import type { ExtractMetadataUseCase } from './extract-metadata.use-case';
import type { GetItemReviewsUseCase } from './get-item-reviews.use-case';
import type { SummarizeItemDescriptionUseCase } from './summarize-item-description.use-case';
import type { ParseImportPreviewUseCase } from './parse-import-preview.use-case';
import type { BulkAddItemsUseCase } from './bulk-add-items.use-case';
import type { SyncItemLinksUseCase } from './sync-item-links.use-case';
import type { SyncItemRelatedUseCase } from './sync-item-related.use-case';
import type { BuildItemClaimProjectionsUseCase } from './build-item-claim-projections.use-case';
import type { ListItemSubstitutionsUseCase } from './list-item-substitutions.use-case';
import type { CreateOwnerSubstitutionUseCase } from './create-owner-substitution.use-case';
import type { CreateClaimerSubstitutionUseCase } from './create-claimer-substitution.use-case';
import type { UpdateItemSubstitutionUseCase } from './update-item-substitution.use-case';
import type { DeleteItemSubstitutionUseCase } from './delete-item-substitution.use-case';
import type { ReorderOwnerSubstitutionsUseCase } from './reorder-owner-substitutions.use-case';

export interface ItemUseCases {
  addItem: AddItemUseCase;
  listItems: ListItemsUseCase;
  claimItem: ClaimItemUseCase;
  claimItemWithLinked: ClaimItemWithLinkedUseCase;
  addItemLink: AddItemLinkUseCase;
  deleteItem: DeleteItemUseCase;
  updateItem: UpdateItemUseCase;
  getFieldDefinitions: GetFieldDefinitionsUseCase;
  unclaimItem: UnclaimItemUseCase;
  unclaimItemWithLinked: UnclaimItemWithLinkedUseCase;
  validateItemAudience: ValidateItemAudienceUseCase;
  extractMetadata: ExtractMetadataUseCase;
  getItemReviews: GetItemReviewsUseCase;
  summarizeItemDescription: SummarizeItemDescriptionUseCase;
  parseImportPreview: ParseImportPreviewUseCase;
  bulkAddItems: BulkAddItemsUseCase;
  syncItemLinks: SyncItemLinksUseCase;
  syncItemRelated: SyncItemRelatedUseCase;
  buildItemClaimProjections: BuildItemClaimProjectionsUseCase;
  listItemSubstitutions: ListItemSubstitutionsUseCase;
  createOwnerSubstitution: CreateOwnerSubstitutionUseCase;
  createClaimerSubstitution: CreateClaimerSubstitutionUseCase;
  updateItemSubstitution: UpdateItemSubstitutionUseCase;
  deleteItemSubstitution: DeleteItemSubstitutionUseCase;
  reorderOwnerSubstitutions: ReorderOwnerSubstitutionsUseCase;
}
