import type { SignupUseCase } from '../../slices/session/use-cases/signup.use-case';
import type { LoginUseCase } from '../../slices/session/use-cases/login.use-case';
import type { UpdateProfileUseCase } from '../../slices/profile/use-cases/update-profile.use-case';
import type { UserPreviewUseCase } from '../../slices/profile/use-cases/user-preview.use-case';
import type { ListCustomThemesUseCase } from '../../slices/themes/use-cases/list-custom-themes.use-case';
import type { SaveCustomThemeUseCase } from '../../slices/themes/use-cases/save-custom-theme.use-case';
import type { DeleteCustomThemeUseCase } from '../../slices/themes/use-cases/delete-custom-theme.use-case';
import type { PasskeyLoginUseCase } from '../../slices/passkeys/use-cases/passkey-login.use-case';
import type { RegisterPasskeyUseCase } from '../../slices/passkeys/use-cases/register-passkey.use-case';
import type { ListPasskeysUseCase } from '../../slices/passkeys/use-cases/list-passkeys.use-case';
import type { DeletePasskeyUseCase } from '../../slices/passkeys/use-cases/delete-passkey.use-case';
import type { TwoFactorLoginUseCase } from '../../slices/session/use-cases/two-factor-login.use-case';
import type { Enable2faUseCase } from '../../slices/two-factor/use-cases/enable-2fa.use-case';
import type { Disable2faUseCase } from '../../slices/two-factor/use-cases/disable-2fa.use-case';
import type { DisableAccountUseCase } from '../../slices/session/use-cases/disable-account.use-case';
import type { DeleteAccountUseCase } from '../../slices/session/use-cases/delete-account.use-case';
import type { GetCurrentUserUseCase } from '../../slices/session/use-cases/get-current-user.use-case';
import type { GetOnboardingStateUseCase } from '../../slices/profile/use-cases/get-onboarding-state.use-case';
import type { CompleteUserOnboardingUseCase } from '../../slices/profile/use-cases/complete-user-onboarding.use-case';
import type { CompleteOwnerOnboardingUseCase } from '../../slices/profile/use-cases/complete-owner-onboarding.use-case';
import type { PatchTutorialUseCase } from '../../slices/profile/use-cases/patch-tutorial.use-case';
import type { BeginOidcLoginUseCase } from '../../slices/oidc/use-cases/begin-oidc-login.use-case';
import type { HandleOidcCallbackUseCase } from '../../slices/oidc/use-cases/handle-oidc-callback.use-case';
import type { ChangePasswordUseCase } from '../../slices/session/use-cases/change-password.use-case';

export interface UseCases {
  signup: SignupUseCase;
  login: LoginUseCase;
  changePassword: ChangePasswordUseCase;
  updateProfile: UpdateProfileUseCase;
  userPreview: UserPreviewUseCase;
  listCustomThemes: ListCustomThemesUseCase;
  saveCustomTheme: SaveCustomThemeUseCase;
  deleteCustomTheme: DeleteCustomThemeUseCase;
  passkeyLogin: PasskeyLoginUseCase;
  registerPasskey: RegisterPasskeyUseCase;
  listPasskeys: ListPasskeysUseCase;
  deletePasskey: DeletePasskeyUseCase;
  twoFactorLogin: TwoFactorLoginUseCase;
  enable2fa: Enable2faUseCase;
  disable2fa: Disable2faUseCase;
  disableAccount: DisableAccountUseCase;
  deleteAccount: DeleteAccountUseCase;
  getCurrentUser: GetCurrentUserUseCase;
  getOnboardingState: GetOnboardingStateUseCase;
  completeUserOnboarding: CompleteUserOnboardingUseCase;
  completeOwnerOnboarding: CompleteOwnerOnboardingUseCase;
  patchTutorial: PatchTutorialUseCase;
  beginOidcLogin: BeginOidcLoginUseCase;
  handleOidcCallback: HandleOidcCallbackUseCase;
}
