export const DEFAULT_AI_IMPORT_CHUNKING_ENABLED = true;
export const DEFAULT_AI_IMPORT_CHUNK_ITEM_LIMIT = 20;
export const AI_IMPORT_CHUNK_ITEM_LIMIT_MIN = 1;
export const AI_IMPORT_CHUNK_ITEM_LIMIT_MAX = 100;
