export const DEFAULT_GRAB_INFO_CONCURRENCY = 3;
export const GRAB_INFO_CONCURRENCY_MIN = 1;
export const GRAB_INFO_CONCURRENCY_MAX = 1000;
export const DEFAULT_GRAB_INFO_CONCURRENCY_UNLIMITED = false;
export const DEFAULT_GRAB_INFO_ACTIVE_STREAM_LIMIT = 16;
export const GRAB_INFO_ACTIVE_STREAM_LIMIT_MIN = 1;
export const GRAB_INFO_ACTIVE_STREAM_LIMIT_MAX = 1000;
