export const DEFAULT_SCRAPE_FETCH_TIMEOUT_MS = 8000;
export const DEFAULT_SCRAPE_PLAYWRIGHT_TIMEOUT_MS = 25000;
export const SCRAPE_FETCH_TIMEOUT_MIN_MS = 1000;
export const SCRAPE_FETCH_TIMEOUT_MAX_MS = 60_000;
export const SCRAPE_PLAYWRIGHT_TIMEOUT_MIN_MS = 1000;
export const SCRAPE_PLAYWRIGHT_TIMEOUT_MAX_MS = 120_000;
