import type { CustomPackSettingsDto } from '../packs';
import type { AiMetadataExtractionPreset } from '../types/ai-metadata-extraction-preset.type';
import type { AiProvider } from '../types/ai-provider.type';
import type { ConnectionType } from '../types/connection-type.type';

export interface SystemSettingsView {
  DbType: ConnectionType;
  DbUrl: string;
  SmtpType: ConnectionType;
  SmtpHost: string;
  SmtpPort: number;
  SmtpUser: string;
  SmtpPass: string;
  SmtpSecure: boolean;
  SmtpFrom: string;
  PublicAppUrl: string;
  AllowSetup: boolean;
  OAuthEnabled: boolean;
  OAuthIssuerUrl: string;
  OAuthClientId: string;
  OAuthClientSecret: string;
  OAuthScopes: string;
  OAuthAutoRegister: boolean;
  OAuthAutoLaunch: boolean;
  AiEnabled: boolean;
  AiWebSearchEnabled: boolean;
  AiWebSearchEndpoint: string;
  AiWebSearchMaxPages: number;
  AiRateLimitEnabled: boolean;
  AiFastProvider: AiProvider;
  AiFastEndpoint: string;
  AiFastApiKey: string;
  AiFastModel: string;
  AiIntelligentProvider: AiProvider;
  AiIntelligentEndpoint: string;
  AiIntelligentApiKey: string;
  AiIntelligentModel: string;
  AiPrompt: string;
  AiDescriptionPrompt: string;
  AiPopulatePrompt: string;
  AiCategoryPrompt: string;
  AiImportPrompt: string;
  AiImportChunkingEnabled: boolean;
  AiImportChunkItemLimit: number;
  AiMetadataExtractionPreset: AiMetadataExtractionPreset;
  AiPageContextMaxChars: number | null;
  AiPopulateMaxTokens: number | null;
  AiMetadataSplitPackCalls: boolean;
  AiEnabledPackIds: string[];
  AiCustomPacks: CustomPackSettingsDto[];
  AiCompletionTimeoutMs: number;
  AiConnectTimeoutMs: number;
  ScrapeFetchTimeoutMs: number;
  ScrapePlaywrightTimeoutMs: number;
  GrabInfoConcurrency: number;
  GrabInfoConcurrencyUnlimited: boolean;
  GrabInfoActiveStreamLimit: number;
  NtfyEnabled: boolean;
  NtfyBaseUrl: string;
  NtfyAuthToken: string;
  NtfyTopicPrefix: string;
  WebPushEnabled: boolean;
  WebPushVapidPublicKey: string;
  WebPushVapidPrivateKey: string;
  WebPushSubject: string;
  FcmEnabled: boolean;
  FcmProjectId: string;
  FcmServiceAccountJson: string;
  GiphyApiKey: string;
  AiDefaultPrompts: {
    Review: string;
    Description: string;
    Populate: string;
    Category: string;
    Import: string;
  };
}
