import type { User } from '../interfaces/user.interface';
import type { TourState } from '../interfaces/tour-state.interface';
import type { UserSearchResult } from '@/modules/friends';
import type { AdminAccountStatus } from '../interfaces/admin-account-status.interface';
import type { CreateOauthUserInput } from '../interfaces/create-oauth-user-input.interface';
import type { CustomTheme } from '../interfaces/custom-theme.interface';
import type { CustomThemeInput } from '../interfaces/custom-theme-input.interface';
import type { DeleteAccountStatus } from '../interfaces/delete-account-status.interface';
import type { EmailVerificationLookup } from '../interfaces/email-verification-lookup.interface';
import type { TwoFactorSecrets } from '../interfaces/two-factor-secrets.interface';
import type { UserUpdateInput } from '../interfaces/user-update-input.interface';

export interface UserRepository {
  findByEmail(email: string): Promise<User | null>;
  findByUsername(username: string): Promise<User | null>;
  findById(id: string): Promise<User | null>;
  findByOauthSub(oauthSub: string): Promise<User | null>;
  create(username: string, email: string | null, firstName: string, lastName: string, authHash: string, isAdmin?: boolean, isOwner?: boolean): Promise<User>;
  createOauthUser(params: CreateOauthUserInput): Promise<User>;
  linkOauthSub(userId: string, oauthSub: string): Promise<User>;
  setOnboarded(id: string, isOnboarded?: boolean): Promise<User>;
  setTour(id: string, tour: TourState): Promise<User>;
  update(id: string, updates: UserUpdateInput): Promise<User>;
  count(): Promise<number>;
  updateLastOnline(id: string): Promise<void>;
  updateLockout(id: string, failedLoginCount: number, lockedUntil: Date | null): Promise<void>;
  resetLockoutAndRecordLogin(id: string): Promise<void>;
  findByEmailVerificationToken(token: string): Promise<EmailVerificationLookup | null>;
  setDefaultUserPolicy(id: string, policyJson: string): Promise<void>;
  countEnabledAdmins(excludeUserId?: string): Promise<number>;
  getAccountStatusForDisable(id: string): Promise<AdminAccountStatus | null>;
  getAccountStatusForDelete(id: string): Promise<DeleteAccountStatus | null>;
  disableAccount(id: string): Promise<void>;
  updatePassword(id: string, authHash: string): Promise<User>;
  deleteAccount(id: string): Promise<void>;
  getTwoFactorSecrets(id: string): Promise<TwoFactorSecrets | null>;
  countMutualFriends(viewerId: string, userId: string): Promise<number>;
  listCustomThemes(userId: string): Promise<CustomTheme[]>;
  findCustomThemeById(themeId: string): Promise<CustomTheme | null>;
  saveCustomTheme(userId: string, theme: CustomThemeInput): Promise<CustomTheme>;
  deleteCustomTheme(userId: string, themeId: string): Promise<void>;
  searchUsers(query: string, excludeId: string): Promise<UserSearchResult[]>;
  isUserDisabled(userId: string): Promise<boolean | null>;
}
