import type { SignupUseCase } from '../application/signup.use-case';
import type { LoginUseCase } from '../application/login.use-case';
import type { UpdateProfileUseCase } from '../application/update-profile.use-case';
import type { UserPreviewUseCase } from '../application/user-preview.use-case';
import type { ListCustomThemesUseCase } from '../application/list-custom-themes.use-case';
import type { SaveCustomThemeUseCase } from '../application/save-custom-theme.use-case';
import type { DeleteCustomThemeUseCase } from '../application/delete-custom-theme.use-case';
import type { PasskeyLoginUseCase } from '../application/passkey-login.use-case';
import type { RegisterPasskeyUseCase } from '../application/register-passkey.use-case';
import type { ListPasskeysUseCase } from '../application/list-passkeys.use-case';
import type { DeletePasskeyUseCase } from '../application/delete-passkey.use-case';
import type { TwoFactorLoginUseCase } from '../application/two-factor-login.use-case';
import type { Setup2faUseCase } from '../application/setup-2fa.use-case';
import type { Enable2faUseCase } from '../application/enable-2fa.use-case';
import type { Disable2faUseCase } from '../application/disable-2fa.use-case';
import type { DisableAccountUseCase } from '../application/disable-account.use-case';
import type { DeleteAccountUseCase } from '../application/delete-account.use-case';
import type { GetCurrentUserUseCase } from '../application/get-current-user.use-case';
import type { GetOnboardingStateUseCase } from '../application/get-onboarding-state.use-case';
import type { CompleteUserOnboardingUseCase } from '../application/complete-user-onboarding.use-case';
import type { CompleteOwnerOnboardingUseCase } from '../application/complete-owner-onboarding.use-case';
import type { BeginOidcLoginUseCase } from '../application/begin-oidc-login.use-case';
import type { HandleOidcCallbackUseCase } from '../application/handle-oidc-callback.use-case';

export interface AuthUseCases {
  signup: SignupUseCase;
  login: LoginUseCase;
  updateProfile: UpdateProfileUseCase;
  userPreview: UserPreviewUseCase;
  listCustomThemes: ListCustomThemesUseCase;
  saveCustomTheme: SaveCustomThemeUseCase;
  deleteCustomTheme: DeleteCustomThemeUseCase;
  passkeyLogin: PasskeyLoginUseCase;
  registerPasskey: RegisterPasskeyUseCase;
  listPasskeys: ListPasskeysUseCase;
  deletePasskey: DeletePasskeyUseCase;
  twoFactorLogin: TwoFactorLoginUseCase;
  setup2fa: Setup2faUseCase;
  enable2fa: Enable2faUseCase;
  disable2fa: Disable2faUseCase;
  disableAccount: DisableAccountUseCase;
  deleteAccount: DeleteAccountUseCase;
  getCurrentUser: GetCurrentUserUseCase;
  getOnboardingState: GetOnboardingStateUseCase;
  completeUserOnboarding: CompleteUserOnboardingUseCase;
  completeOwnerOnboarding: CompleteOwnerOnboardingUseCase;
  beginOidcLogin: BeginOidcLoginUseCase;
  handleOidcCallback: HandleOidcCallbackUseCase;
}
