import type { AddItemUseCase } from '../../slices/catalog/use-cases/add-item.use-case';
import type { DeleteItemUseCase } from '../../slices/catalog/use-cases/delete-item.use-case';
import type { GetFieldDefinitionsUseCase } from '../../slices/catalog/use-cases/get-field-definitions.use-case';
import type { ListItemsUseCase } from '../../slices/catalog/use-cases/list-items.use-case';
import type { UpdateItemUseCase } from '../../slices/catalog/use-cases/update-item.use-case';
import type { ValidateItemAudienceUseCase } from '../../slices/catalog/use-cases/validate-item-audience.use-case';
import type { BuildItemClaimProjectionsUseCase } from '../../slices/claims/use-cases/build-item-claim-projections.use-case';
import type { ClaimItemUseCase } from '../../slices/claims/use-cases/claim-item.use-case';
import type { ClaimItemWithLinkedUseCase } from '../../slices/claims/use-cases/claim-item-with-linked.use-case';
import type { UnclaimItemUseCase } from '../../slices/claims/use-cases/unclaim-item.use-case';
import type { UnclaimItemWithLinkedUseCase } from '../../slices/claims/use-cases/unclaim-item-with-linked.use-case';
import type { BulkAddItemsUseCase } from '../../slices/import/use-cases/bulk-add-items.use-case';
import type { ParseImportPreviewUseCase } from '../../slices/import/use-cases/parse-import-preview.use-case';
import type { AddItemLinkUseCase } from '../../slices/links/use-cases/add-item-link.use-case';
import type { SyncItemLinksUseCase } from '../../slices/links/use-cases/sync-item-links.use-case';
import type { SyncItemRelatedUseCase } from '../../slices/links/use-cases/sync-item-related.use-case';
import type { ExtractMetadataUseCase } from '../../slices/metadata/use-cases/extract-metadata.use-case';
import type { GetItemReviewsUseCase } from '../../slices/metadata/use-cases/get-item-reviews.use-case';
import type { PromoteScrapedImageToPhotosUseCase } from '../../slices/metadata/use-cases/promote-scraped-image-to-photos.use-case';
import type { SummarizeItemDescriptionUseCase } from '../../slices/metadata/use-cases/summarize-item-description.use-case';
import type { CreateClaimerSubstitutionUseCase } from '../../slices/substitutions/use-cases/create-claimer-substitution.use-case';
import type { CreateOwnerSubstitutionUseCase } from '../../slices/substitutions/use-cases/create-owner-substitution.use-case';
import type { DeleteItemSubstitutionUseCase } from '../../slices/substitutions/use-cases/delete-item-substitution.use-case';
import type { ListItemSubstitutionsUseCase } from '../../slices/substitutions/use-cases/list-item-substitutions.use-case';
import type { ReorderOwnerSubstitutionsUseCase } from '../../slices/substitutions/use-cases/reorder-owner-substitutions.use-case';
import type { UpdateItemSubstitutionUseCase } from '../../slices/substitutions/use-cases/update-item-substitution.use-case';

export interface UseCases {
  addItem: AddItemUseCase;
  listItems: ListItemsUseCase;
  claimItem: ClaimItemUseCase;
  claimItemWithLinked: ClaimItemWithLinkedUseCase;
  addItemLink: AddItemLinkUseCase;
  deleteItem: DeleteItemUseCase;
  updateItem: UpdateItemUseCase;
  getFieldDefinitions: GetFieldDefinitionsUseCase;
  unclaimItem: UnclaimItemUseCase;
  unclaimItemWithLinked: UnclaimItemWithLinkedUseCase;
  validateItemAudience: ValidateItemAudienceUseCase;
  extractMetadata: ExtractMetadataUseCase;
  getItemReviews: GetItemReviewsUseCase;
  summarizeItemDescription: SummarizeItemDescriptionUseCase;
  parseImportPreview: ParseImportPreviewUseCase;
  bulkAddItems: BulkAddItemsUseCase;
  syncItemLinks: SyncItemLinksUseCase;
  syncItemRelated: SyncItemRelatedUseCase;
  buildItemClaimProjections: BuildItemClaimProjectionsUseCase;
  listItemSubstitutions: ListItemSubstitutionsUseCase;
  createOwnerSubstitution: CreateOwnerSubstitutionUseCase;
  createClaimerSubstitution: CreateClaimerSubstitutionUseCase;
  updateItemSubstitution: UpdateItemSubstitutionUseCase;
  deleteItemSubstitution: DeleteItemSubstitutionUseCase;
  reorderOwnerSubstitutions: ReorderOwnerSubstitutionsUseCase;
  promoteScrapedImageToPhotos: PromoteScrapedImageToPhotosUseCase;
}
